DELETE FROM classification;
INSERT INTO classification VALUES (NULL,100,'Formations generales');
INSERT INTO classification VALUES (NULL,110,'Specialites pluri-scientifiques');
INSERT INTO classification VALUES (NULL,111,'Physique-Chimie');
INSERT INTO classification VALUES (NULL,112,'Chimie-biologie, biochimie');
INSERT INTO classification VALUES (NULL,113,'Sciences naturelles');
INSERT INTO classification VALUES (NULL,114,'Mathematiques');
INSERT INTO classification VALUES (NULL,115,'Physique');
INSERT INTO classification VALUES (NULL,116,'Chimie');
INSERT INTO classification VALUES (NULL,117,'Sciences de la terre');
INSERT INTO classification VALUES (NULL,118,'Sciences de la vie');
INSERT INTO classification VALUES (NULL,120,'Specialites pluridisciplinaires sciences humaines et droit');
INSERT INTO classification VALUES (NULL,121,'Geographie');
INSERT INTO classification VALUES (NULL,122,'Economie');
INSERT INTO classification VALUES (NULL,123,'Sciences sociales');
INSERT INTO classification VALUES (NULL,124,'Psychologie');
INSERT INTO classification VALUES (NULL,125,'Linguistique');
INSERT INTO classification VALUES (NULL,126,'Histoire');
INSERT INTO classification VALUES (NULL,127,'Philosophie, ethique et theologie');
INSERT INTO classification VALUES (NULL,128,'Droit, sciences politiques');
INSERT INTO classification VALUES (NULL,130,'Specialites litteraires et artistiques plurivalentes');
INSERT INTO classification VALUES (NULL,131,'Francais, litterature et civilisation francaise');
INSERT INTO classification VALUES (NULL,132,'Arts plastiques');
INSERT INTO classification VALUES (NULL,133,'Musique, arts du spectacle');
INSERT INTO classification VALUES (NULL,134,'Autres disciplines artistiques et specialites artistiques plurivalentes');
INSERT INTO classification VALUES (NULL,135,'Langues et civilisations anciennes');
INSERT INTO classification VALUES (NULL,136,'Langues vivantes, civilisations etrangeres et regionales');
INSERT INTO classification VALUES (NULL,200,'Technologies industrielles fondamentales (genie industriel et procedes de transformation, specialites a dominante fonctionnelle)');
INSERT INTO classification VALUES (NULL,201,'Technologies de commandes des transformations industrielles (automatismes et robotique industriels, informatique industrielle)');
INSERT INTO classification VALUES (NULL,210,'Specialites plurivalentes de l''agronomie et de l''agriculture');
INSERT INTO classification VALUES (NULL,211,'Productions vegetales, cultures specialisees et protection des cultures (horticulture, viticulture, arboriculture fruitiere...)');
INSERT INTO classification VALUES (NULL,212,'Production animales, elevage specialise, aquaculture, soins aux animaux (y compris veterinaire)');
INSERT INTO classification VALUES (NULL,213,'Forets, espaces naturels, faunes sauvage, peche');
INSERT INTO classification VALUES (NULL,214,'Amenagement paysager (parcs, jardins, espaces verts, terrains de sport)');
INSERT INTO classification VALUES (NULL,220,'Specialites pluritechnologiques des transformations');
INSERT INTO classification VALUES (NULL,221,'Agro-alimentaire, alimentation, cuisine');
INSERT INTO classification VALUES (NULL,222,'Transformations chimiques et apparentees (y compris industrie pharmaceutique)');
INSERT INTO classification VALUES (NULL,223,'Metallurgie (y compris siderurgie, fonderie, non-ferreux..)');
INSERT INTO classification VALUES (NULL,224,'Materiaux de construction, verre, ceramique');
INSERT INTO classification VALUES (NULL,225,'Plasturgie, materiaux composites');
INSERT INTO classification VALUES (NULL,226,'Papier, carton');
INSERT INTO classification VALUES (NULL,227,'Energie, genie climatique (y compris energie nucleaire, thermique, hydraulique, utilites : froid, climatisation, chauffage)');
INSERT INTO classification VALUES (NULL,230,'Specialites pluritechnologiques, genie civil, construction, bois');
INSERT INTO classification VALUES (NULL,231,'Mines et carrieres, genie civil, topographie');
INSERT INTO classification VALUES (NULL,232,'Batiment : construction et couverture');
INSERT INTO classification VALUES (NULL,233,'Batiment : finitions');
INSERT INTO classification VALUES (NULL,234,'Travail du bois et de l''ameublement');
INSERT INTO classification VALUES (NULL,240,'Specialites pluritechnologiques materiaux souples');
INSERT INTO classification VALUES (NULL,241,'Textile');
INSERT INTO classification VALUES (NULL,242,'Habillement (y compris mode, couture)');
INSERT INTO classification VALUES (NULL,243,'Cuirs et peaux');
INSERT INTO classification VALUES (NULL,250,'Specialites pluritechnologiques mecanique-electricite (y compris maintenance mecano-electrique)');
INSERT INTO classification VALUES (NULL,251,'Mecanique generale et de precision, usinage');
INSERT INTO classification VALUES (NULL,252,'Moteurs et mecanique auto');
INSERT INTO classification VALUES (NULL,253,'Mecanique aeronautique et spatiale');
INSERT INTO classification VALUES (NULL,254,'Structures metalliques (y compris soudure, carrosserie, coque bateau, cellule avion)');
INSERT INTO classification VALUES (NULL,255,'Electricite, electronique (non compris automatismes, productique)');
INSERT INTO classification VALUES (NULL,300,'Specialites plurivalentes des services');
INSERT INTO classification VALUES (NULL,310,'Specialites plurivalentes des echanges et de la gestion (y c administration generale des entreprises');
INSERT INTO classification VALUES (NULL,311,'Transport, manutention, magasinage');
INSERT INTO classification VALUES (NULL,312,'Commerce, vente');
INSERT INTO classification VALUES (NULL,313,'Finances, banque, assurances');
INSERT INTO classification VALUES (NULL,314,'Comptabilite, gestion');
INSERT INTO classification VALUES (NULL,315,'Ressources humaines, gestion du personnel, gestion de l''emploi');
INSERT INTO classification VALUES (NULL,320,'Specialite plurivalentes de la communication');
INSERT INTO classification VALUES (NULL,321,'Journalisme et communication (y compris communication graphique et publicite)');
INSERT INTO classification VALUES (NULL,322,'Techniques de l''impri l''imprimerie et de l''edition');
INSERT INTO classification VALUES (NULL,323,'Techniques de l''image et du son, metiers connexes du spectacle');
INSERT INTO classification VALUES (NULL,324,'Secretariat, bureautique');
INSERT INTO classification VALUES (NULL,325,'Documentation, bibliotheques, administration des donnees');
INSERT INTO classification VALUES (NULL,326,'Informatique, traitement de l''information, reseaux de transmission des donnees');
INSERT INTO classification VALUES (NULL,330,'Specialites plurivalentes sanitaires et sociales');
INSERT INTO classification VALUES (NULL,331,'Sante');
INSERT INTO classification VALUES (NULL,332,'Travail social');
INSERT INTO classification VALUES (NULL,333,'Enseignement, formation');
INSERT INTO classification VALUES (NULL,334,'Accueil, hotellerie, tourisme');
INSERT INTO classification VALUES (NULL,335,'Animation culturelle, sportive et de loisirs');
INSERT INTO classification VALUES (NULL,336,'Coiffure, esthetique et autres specialites des services aux personnes');
INSERT INTO classification VALUES (NULL,340,'Specialites plurivalentes des services a la collectivite');
INSERT INTO classification VALUES (NULL,341,'Amenagement du territoire, developpement, urbanisme');
INSERT INTO classification VALUES (NULL,342,'Protection et developpement du patrimoine');
INSERT INTO classification VALUES (NULL,343,'Nettoyage, assainissement, protection de l''environnement');
INSERT INTO classification VALUES (NULL,344,'Securite des biens et des personnes, police, surveillance (y compris hygiene et securite)');
INSERT INTO classification VALUES (NULL,345,'Application des droits et statuts des personnes');
INSERT INTO classification VALUES (NULL,346,'Specialites militaires');
INSERT INTO classification VALUES (NULL,410,'Specialites concernant plusieurs capacites');
INSERT INTO classification VALUES (NULL,411,'Pratiques sportives (y compris arts martiaux)');
INSERT INTO classification VALUES (NULL,412,'Developpement des capacites mentales et apprentissages de base');
INSERT INTO classification VALUES (NULL,413,'Developpement des capacites comportementales et relationnelles');
INSERT INTO classification VALUES (NULL,414,'Developpement des capacites individuelles d''organisation');
INSERT INTO classification VALUES (NULL,415,'Developpement des capacites d''orientation, d''insertion ou de reinsertion sociales et professionnelles');
INSERT INTO classification VALUES (NULL,421,'Jeux et activites specifiques de loisirs');
INSERT INTO classification VALUES (NULL,422,'Economie et activites domestiques');
INSERT INTO classification VALUES (NULL,423,'Vie familiale, vie sociale et autres formations au developpement personnel');
