CREATE TABLE IF NOT EXISTS utilisateurType (
	UTILISATEURTYPE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	UTILISATEURTYPE_TYPE VARCHAR(15) NOT NULL
);

INSERT INTO utilisateurType (UTILISATEURTYPE_TYPE) VALUES ('Admin'),('Formateur'), ('Comptable');

CREATE TABLE IF NOT EXISTS utilisateur  (
UTILISATEUR_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
UTILISATEUR_MAIL VARCHAR(50) NOT NULL,
UTILISATEUR_MOT_DE_PASSE VARCHAR(30) NOT NULL,
UTILISATEUR_NOM VARCHAR(50) NOT NULL,
UTILISATEUR_PRENOM VARCHAR(50) NOT NULL,
UTILISATEUR_UTILISATEURTYPE INT NOT NULL,
UTILISATEUR_ADRESSE VARCHAR(250) NOT NULL,
UTILISATEUR_CODE_POSTAL VARCHAR(5) NOT NULL,
UTILISATEUR_VILLE VARCHAR(30) NOT NULL,
UTILISATEUR_TEL VARCHAR(10) NOT NULL,
UTILISATEUR_ACTIVE BOOLEAN NOT NULL DEFAULT 0,
FOREIGN KEY (UTILISATEUR_UTILISATEURTYPE) REFERENCES utilisateurType(UTILISATEURTYPE_ID)
);

CREATE TABLE IF NOT EXISTS competence (
COMPETENCE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
COMPETENCE_LIBELLE VARCHAR(30) NOT NULL,
COMPETENCE_DEFAUT BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS utilisateur_competence (
	UC_UTILISATEUR INT NOT NULL,
	UC_COMPETENCE INT NOT NULL,
	UC_NIVEAU INT NOT NULL,
	PRIMARY KEY (UC_UTILISATEUR, UC_COMPETENCE),
	FOREIGN KEY (UC_UTILISATEUR ) REFERENCES utilisateur(UTILISATEUR_ID),
	FOREIGN KEY (UC_COMPETENCE ) REFERENCES competence(COMPETENCE_ID)
);

CREATE TABLE IF NOT EXISTS classification(
	CLASSIFICATION_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CLASSIFICATION_CODE_INSEE INT NOT NULL,
	CLASSIFICATION_LIBELLE VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS formationType(
	FORMATIONTYPE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FORMATIONTYPE_LIBELLE VARCHAR(30) NOT NULL
);

INSERT INTO formationType(FORMATIONTYPE_LIBELLE ) VALUES ('Intra-entreprise'),('Inter-entreprises'), ('Sous-traitance');

CREATE TABLE IF NOT EXISTS formation (
	FORMATION_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FORMATION_INTITULE VARCHAR(250) NOT NULL,
	FORMATION_DATE_DEMANDE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FORMATION_DUREE INT NOT NULL,
	FORMATION_FORMATEUR INT NOT NULL,
	FORMATION_FORMATIONTYPE INT NOT NULL,
	FORMATION_CLASSIFICATION INT NOT NULL,
	FORMATION_CERTIFICATION BOOLEAN NOT NULL DEFAULT 0,
	FOREIGN KEY (FORMATION_FORMATIONTYPE) REFERENCES formationType(FORMATIONTYPE_ID),
	FOREIGN KEY (FORMATION_CLASSIFICATION) REFERENCES classification(CLASSIFICATION_ID),
	FOREIGN KEY (FORMATION_FORMATEUR ) REFERENCES utilisateur(UTILISATEUR_ID)
);

CREATE TABLE IF NOT EXISTS formation_date (
	FD_FORMATION INT NOT NULL,
	FD_DATE_DEBUT TIMESTAMP NOT NULL,
	FD_DATE_FIN TIMESTAMP NOT NULL,
	PRIMARY KEY (FD_FORMATION, FD_DATE_DEBUT),
	FOREIGN KEY (FD_FORMATION ) REFERENCES formation(FORMATION_ID)
);

CREATE TABLE IF NOT EXISTS client (
	CLIENT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CLIENT_RAISON_SOCIALE VARCHAR(250) NOT NULL,
	CLIENT_ADRESSE VARCHAR(250) NOT NULL,
	CLIENT_CODE_POSTAL VARCHAR(5) NOT NULL,
	CLIENT_VILLE VARCHAR(30) NOT NULL,
	CLIENT_CONTACT_NOM VARCHAR(50) NOT NULL,
	CLIENT_CONTACT_PRENOM VARCHAR(50) NOT NULL,
	CLIENT_CONTACT_MAIL VARCHAR(50)
);
	
CREATE TABLE IF NOT EXISTS participant (
	PARTICIPANT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PARTICIPANT_NOM VARCHAR(50) NOT NULL,
	PARTICIPANT_PRENOM VARCHAR(50) NOT NULL,
	PARTICIPANT_DATE_NAISSANCE DATE NOT NULL,
	PARTICIPANT_ADRESSE  VARCHAR(250) NOT NULL,
	PARTICIPANT_CODE_POSTAL  VARCHAR(5) NOT NULL,
	PARTICIPANT_VILLE  VARCHAR(50) NOT NULL,
	PARTICIPANT_SOCIETE INT NOT NULL,
	PARTICIPANT_MAIL  VARCHAR(50) NOT NULL,
	PARTICIPANT_TEL  VARCHAR(10) NOT NULL,
	PARTICIPANT_INFORME BOOLEAN NOT NULL DEFAULT 1,
	FOREIGN KEY (PARTICIPANT_SOCIETE) REFERENCES client(CLIENT_ID)
);

CREATE TABLE IF NOT EXISTS formation_client_participant (
	FCP_FORMATION INT NOT NULL,
	FCP_CLIENT INT NOT NULL,
	FCP_PARTICIPANT INT NOT NULL,
	PRIMARY KEY (FCP_FORMATION, FCP_CLIENT, FCP_PARTICIPANT),
	FOREIGN KEY (FCP_FORMATION) REFERENCES formation(FORMATION_ID),
	FOREIGN KEY (FCP_CLIENT) REFERENCES client(CLIENT_ID),
	FOREIGN KEY (FCP_PARTICIPANT) REFERENCES participant(PARTICIPANT_ID)
);

CREATE TABLE IF NOT EXISTS facture (
	FACTURE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FACTURE_DATE DATE NOT NULL,
	FACTURE_CLIENT INT NOT NULL,
	FACTURE_FORMATION INT NOT NULL,
	FACTURE_REGLEE BOOLEAN NOT NULL DEFAULT 0,
	FOREIGN KEY (FACTURE_CLIENT ) REFERENCES client(CLIENT_ID),
	FOREIGN KEY (FACTURE_FORMATION ) REFERENCES formation(FORMATION_ID)
);

CREATE TABLE IF NOT EXISTS devis (
	DEVIS_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DEVIS_DATE DATE NOT NULL,
	DEVIS_CLIENT INT NOT NULL,
	DEVIS_FORMATION INT NOT NULL,
	DEVIS_REGLEE BOOLEAN NOT NULL DEFAULT 0,
	FOREIGN KEY (DEVIS_CLIENT ) REFERENCES client(CLIENT_ID),
	FOREIGN KEY (DEVIS_FORMATION ) REFERENCES formation(FORMATION_ID)
);
